# Generated by Django 5.2.7 on 2025-11-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='mail',
            new_name='email',
        ),
    ]
